version: '3.8'

services:
  core:
    build:
      context: ../../services/core
      dockerfile: build/local/Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  web-client:
    build:
      context: ../../services/web-client
      dockerfile: build/local/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "../../services/web-client:/app"

  postgres:
      image: postgres:15.0
      environment:
        POSTGRES_DB: "yapp"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "admin"
        PGDATA: "/data"
      ports:
        - "5432:5432"
      volumes:
        - "postgres:/data"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres: {}
  pgadmin: {}