version: '3.8'

services:
  core:
    build:
      context: ../../services/core
      dockerfile: build/local/Dockerfile
    ports:
      - "3001:3001"

  web-client:
    build:
      context: ../../services/web-client
      dockerfile: build/local/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "../../services/web-client:/app"